### ISSUE TITLE
Any chance of isolating some dependencies with features?

### ISSUE THREAD

**Issue by IAPark** [zurawiki/tiktoken-rs#10]
In particular `async-openai` is fairly heavy in terms of dependencies for what it's used for here and it blocked compiling my attempted binding for ruby [tiktoken_ruby](https://github.com/iapark/tiktoken_ruby) on some platforms because of some sort of difficulty with openssl. 

Also side note, thanks for putting together this little library, it made a ruby wrapper much easier gave hints about how it all needs to fit together

**Comment by zurawiki** [comment]
Happy I could help! I agree that the dependencies are heavier than I would like.

Can you see if the new 0.3.3 version helps. The async-openai library migrated to rusttls which should address the openssl issue. I'll see if in a future version we can trim down the deps further

**Comment by IAPark** [comment]
Great, the 0.3.3 version does indeed allow it to compile. I might keep on using a fork without chat message length support though for now, because It still explodes the size a bit

**Comment by zurawiki** [comment]
Closing due to #15 landing
