### ISSUE TITLE
Make the crate independent of async_openai

### ISSUE THREAD

**Issue by thedenisnikulin** [zurawiki/tiktoken-rs#13]
The crate seem to use `async_openai` only for messages, but this a pretty small thing that should not require to bring in a whole crate to its dependencies. I just want to use this crate with other implementation of openai api wrapper, not `async_openai`, but it's the only things that comes in the way

**Comment by zurawiki** [comment]
Hi I'm heard that feedback from other issues as well #10 . Marking this issue as a duplicate so we can focus efforts on addressing this
