### ISSUE TITLE
Expose `_decode_native`?

### ISSUE THREAD

**Issue by Palmik** [zurawiki/tiktoken-rs#27]
Hey, thanks for the library.

My use case is that I want to split text into tokens, and then split it into chunks based on that. Splitting naively may result in invalid utf-8 (if the token is not at a unicode boundary).

There are different ways to deal with this, in perfect world, I would know which tokens end a unicode character, and only consider those, but that's probably not feasible without major changes.

Alternatively, if I have access to the output of `_decode_native`, I can for example trim the last token(s) or use `from_utf8_lossy`.

What are your thoughts?

**Comment by zurawiki** [comment]
I think exposing this function makes sense for developers that want to handle their own encoding. We should take care to  ensure the interface is maintainable going forward.

**Comment by mirsella** [comment]
In the meantime https://github.com/mirsella/tiktoken-rs
```
tiktoken-rs = { git = "https://github.com/mirsella/tiktoken-rs", rev = "9a1affa" }
```

**Comment by zurawiki** [comment]
Hi @mirsella @Palmik , tiktoken-rs v0.5.6 exposed the `_decode_native` methods.

See the docs below:
https://docs.rs/tiktoken-rs/0.5.6/tiktoken_rs/struct.CoreBPE.html#method._decode_native

I will close out this issue.

**Comment by mirsella** [comment]
thanks you for the heads up !
