### ISSUE TITLE
Don't arbitrarily enforce versions please

### ISSUE THREAD

**Issue by aristotaloss** [zurawiki/tiktoken-rs#37]
```
tiktoken-rs v0.5.3 cannot be built because it requires rustc 1.72.0 or newer, while the currently active rustc version is 1.71.1
```

There's nothing here that warrants enforcing the latest version (literally):
https://blog.rust-lang.org/2023/08/24/Rust-1.72.0.html

**Comment by zurawiki** [comment]
Thanks for the feedback @aristotaloss . I am publishing a new release in v0.5.4 that lowers the MSRV to the greatest common minimum of our dependencies which from local testing with `cargo msrv` seems to be 1.61.0. Note that optional crates like python and async-openai are not guaranteed to work on the MSRV specifcied.
