### ISSUE TITLE
Add `gpt-4-1106-preview`

### ISSUE THREAD

**Issue by JosephTLyons** [zurawiki/tiktoken-rs#46]
The preview of the gpt-4 turbo is out:

https://help.openai.com/en/articles/8555510-gpt-4-turbo

It would be great to have support for this model!

**Comment by zurawiki** [comment]
This is definitely something we want to support. I don't have time this weekend, but I'm open to reviewing a PR

**Comment by zurawiki** [comment]
Merged! Thanks for your help @JosephTLyons
